"""initial schema

Revision ID: 36be3f852e46
Revises:
Create Date: 2026-03-25 11:04:14.515520

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36be3f852e46"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "entities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "PERSON",
                "TASK",
                "COMMIT_PR",
                "DEPLOY",
                "INCIDENT",
                "ERROR_EVENT",
                "METRIC_SNAPSHOT",
                "FEATURE",
                "GOAL",
                "DOCUMENT",
                "DECISION",
                name="entity_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "LINEAR",
                "GITHUB",
                "SLACK",
                "NOTION",
                "DATADOG",
                "SENTRY",
                "PAGERDUTY",
                "AMPLITUDE",
                "POSTHOG",
                "FIGMA",
                "MANUAL",
                name="source_type",
            ),
            nullable=False,
        ),
        sa.Column("source_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("canonical_name", sa.String(length=512), nullable=False),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entities_org_id"), "entities", ["org_id"], unique=False)
    op.create_index("ix_entities_org_type", "entities", ["org_id", "type"], unique=False)
    op.create_index("ix_entities_source_ids", "entities", ["source_ids"], unique=False, postgresql_using="gin")
    op.create_index(op.f("ix_entities_type"), "entities", ["type"], unique=False)
    op.create_table(
        "oauth_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "connector",
            sa.Enum(
                "LINEAR",
                "GITHUB",
                "SLACK",
                "NOTION",
                "DATADOG",
                "SENTRY",
                "PAGERDUTY",
                "AMPLITUDE",
                "POSTHOG",
                "FIGMA",
                "MANUAL",
                name="source_type",
            ),
            nullable=False,
        ),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scopes", sa.String(length=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "connector", name="uq_token_org_connector"),
    )
    op.create_table(
        "sync_states",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "connector",
            sa.Enum(
                "LINEAR",
                "GITHUB",
                "SLACK",
                "NOTION",
                "DATADOG",
                "SENTRY",
                "PAGERDUTY",
                "AMPLITUDE",
                "POSTHOG",
                "FIGMA",
                "MANUAL",
                name="source_type",
            ),
            nullable=False,
        ),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cursor", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Enum("IDLE", "SYNCING", "ERROR", name="sync_status"), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "connector", name="uq_sync_org_connector"),
    )
    op.create_table(
        "edges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("from_entity_id", sa.UUID(), nullable=False),
        sa.Column("to_entity_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "OWNS",
                "BLOCKS",
                "DEPENDS_ON",
                "AUTHORED",
                "MENTIONED_IN",
                "SHIPS_TO",
                "MEASURES",
                "CAUSED_BY",
                "TAGGED_TO",
                "CONFLICTS_WITH",
                name="edge_type",
            ),
            nullable=False,
        ),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("from_entity_id", "to_entity_id", "type", name="uq_edge_triple"),
    )
    op.create_index(op.f("ix_edges_from_entity_id"), "edges", ["from_entity_id"], unique=False)
    op.create_index("ix_edges_from_type", "edges", ["from_entity_id", "type"], unique=False)
    op.create_index(op.f("ix_edges_org_id"), "edges", ["org_id"], unique=False)
    op.create_index(op.f("ix_edges_to_entity_id"), "edges", ["to_entity_id"], unique=False)
    op.create_index("ix_edges_to_type", "edges", ["to_entity_id", "type"], unique=False)
    op.create_index(op.f("ix_edges_type"), "edges", ["type"], unique=False)
    op.create_table(
        "org_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("person_entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("ENGINEER", "PM", "EM", "CTO", "VP_ENG", "VP_PRODUCT", "DESIGNER", name="role_type"),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=True),
        sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "email", name="uq_member_org_email"),
    )
    op.create_table(
        "urgency_scores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("score_components", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("goal_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("person_id", "entity_id", name="uq_score_person_entity"),
    )
    op.create_index("ix_urgency_org_person", "urgency_scores", ["org_id", "person_id"], unique=False)
    op.create_table(
        "briefings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_member_id", sa.UUID(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "delivery_status",
            sa.Enum("PENDING", "SENT", "FAILED", name="delivery_status"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_member_id"],
            ["org_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_briefings_member_date", "briefings", ["org_member_id", "generated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_briefings_member_date", table_name="briefings")
    op.drop_table("briefings")
    op.drop_index("ix_urgency_org_person", table_name="urgency_scores")
    op.drop_table("urgency_scores")
    op.drop_table("org_members")
    op.drop_index(op.f("ix_edges_type"), table_name="edges")
    op.drop_index("ix_edges_to_type", table_name="edges")
    op.drop_index(op.f("ix_edges_to_entity_id"), table_name="edges")
    op.drop_index(op.f("ix_edges_org_id"), table_name="edges")
    op.drop_index("ix_edges_from_type", table_name="edges")
    op.drop_index(op.f("ix_edges_from_entity_id"), table_name="edges")
    op.drop_table("edges")
    op.drop_table("sync_states")
    op.drop_table("oauth_tokens")
    op.drop_index(op.f("ix_entities_type"), table_name="entities")
    op.drop_index("ix_entities_source_ids", table_name="entities", postgresql_using="gin")
    op.drop_index("ix_entities_org_type", table_name="entities")
    op.drop_index(op.f("ix_entities_org_id"), table_name="entities")
    op.drop_table("entities")
    op.drop_table("organizations")
    # ### end Alembic commands ###
